import { fileURLToPath } from "node:url";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import type { Db } from "./client.ts";

// SQL migrations generated by drizzle-kit (plus the hand-written 0000_extensions.sql), applied in order.
// Already-applied migrations are tracked by drizzle in `drizzle.__drizzle_migrations`, so this is idempotent.
export const MIGRATIONS_FOLDER = fileURLToPath(new URL("./migrations", import.meta.url));

export async function runMigrations(db: Db): Promise<void> {
  await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
}
